name: ${project.name}
main: net.azisaba.simpletrade.SimpleTrade
version: ${project.version}
author: siloneco
description: ${project.description}
website: ${project.url}
commands:
  trade:
    usage: /trade <player>
    permission: simpletrade.command.trade
permissions:
  simpletrade.command.trade:
    default: true